version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Master99
  node:
    image: node:10-slim
    container_name: node-container
    working_dir: /home/node/app
    volumes:
      - ./api:/home/node/app
    command:
      bash -c "npm install && npm start"
    ports:
      - "9001:9001"
  web:
    image: "php:7.4-apache"
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db